tap "astronomer/tap"
tap "caskroom/cask"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "gh"
brew "sbt"
brew "scala"
brew "spark"
brew "zsh"
brew "astronomer/tap/astro", link: false
